/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as ComparateurRouteImport } from './routes/comparateur'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as ExcursionsRouteImport } from './routes/excursions'
import { Route as HebergementRouteImport } from './routes/hebergement'
import { Route as MonVoyageRouteImport } from './routes/mon-voyage'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as TransportAeroportRouteImport } from './routes/transport-aeroport'
import { Route as ApiCheckoutCmiCallbackRouteImport } from './routes/api/checkout/cmi-callback'
import { Route as ApiCheckoutStripeWebhookRouteImport } from './routes/api/checkout/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparateurRoute = ComparateurRouteImport.update({
  id: '/comparateur',
  path: '/comparateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsRoute = ExcursionsRouteImport.update({
  id: '/excursions',
  path: '/excursions',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementRoute = HebergementRouteImport.update({
  id: '/hebergement',
  path: '/hebergement',
  getParentRoute: () => rootRouteImport,
} as any)
const MonVoyageRoute = MonVoyageRouteImport.update({
  id: '/mon-voyage',
  path: '/mon-voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportAeroportRoute = TransportAeroportRouteImport.update({
  id: '/transport-aeroport',
  path: '/transport-aeroport',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutCmiCallbackRoute = ApiCheckoutCmiCallbackRouteImport.update({
  id: '/api/checkout/cmi-callback',
  path: '/api/checkout/cmi-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutStripeWebhookRoute =
  ApiCheckoutStripeWebhookRouteImport.update({
    id: '/api/checkout/stripe-webhook',
    path: '/api/checkout/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/comparateur': typeof ComparateurRoute
  '/confirmation': typeof ConfirmationRoute
  '/culture': typeof CultureRoute
  '/excursions': typeof ExcursionsRoute
  '/hebergement': typeof HebergementRoute
  '/mon-voyage': typeof MonVoyageRoute
  '/panier': typeof PanierRoute
  '/transport-aeroport': typeof TransportAeroportRoute
  '/api/checkout/cmi-callback': typeof ApiCheckoutCmiCallbackRoute
  '/api/checkout/stripe-webhook': typeof ApiCheckoutStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/comparateur': typeof ComparateurRoute
  '/confirmation': typeof ConfirmationRoute
  '/culture': typeof CultureRoute
  '/excursions': typeof ExcursionsRoute
  '/hebergement': typeof HebergementRoute
  '/mon-voyage': typeof MonVoyageRoute
  '/panier': typeof PanierRoute
  '/transport-aeroport': typeof TransportAeroportRoute
  '/api/checkout/cmi-callback': typeof ApiCheckoutCmiCallbackRoute
  '/api/checkout/stripe-webhook': typeof ApiCheckoutStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/comparateur': typeof ComparateurRoute
  '/confirmation': typeof ConfirmationRoute
  '/culture': typeof CultureRoute
  '/excursions': typeof ExcursionsRoute
  '/hebergement': typeof HebergementRoute
  '/mon-voyage': typeof MonVoyageRoute
  '/panier': typeof PanierRoute
  '/transport-aeroport': typeof TransportAeroportRoute
  '/api/checkout/cmi-callback': typeof ApiCheckoutCmiCallbackRoute
  '/api/checkout/stripe-webhook': typeof ApiCheckoutStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circuits'
    | '/comparateur'
    | '/confirmation'
    | '/culture'
    | '/excursions'
    | '/hebergement'
    | '/mon-voyage'
    | '/panier'
    | '/transport-aeroport'
    | '/api/checkout/cmi-callback'
    | '/api/checkout/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuits'
    | '/comparateur'
    | '/confirmation'
    | '/culture'
    | '/excursions'
    | '/hebergement'
    | '/mon-voyage'
    | '/panier'
    | '/transport-aeroport'
    | '/api/checkout/cmi-callback'
    | '/api/checkout/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/circuits'
    | '/comparateur'
    | '/confirmation'
    | '/culture'
    | '/excursions'
    | '/hebergement'
    | '/mon-voyage'
    | '/panier'
    | '/transport-aeroport'
    | '/api/checkout/cmi-callback'
    | '/api/checkout/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitsRoute: typeof CircuitsRoute
  ComparateurRoute: typeof ComparateurRoute
  ConfirmationRoute: typeof ConfirmationRoute
  CultureRoute: typeof CultureRoute
  ExcursionsRoute: typeof ExcursionsRoute
  HebergementRoute: typeof HebergementRoute
  MonVoyageRoute: typeof MonVoyageRoute
  PanierRoute: typeof PanierRoute
  TransportAeroportRoute: typeof TransportAeroportRoute
  ApiCheckoutCmiCallbackRoute: typeof ApiCheckoutCmiCallbackRoute
  ApiCheckoutStripeWebhookRoute: typeof ApiCheckoutStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparateur': {
      id: '/comparateur'
      path: '/comparateur'
      fullPath: '/comparateur'
      preLoaderRoute: typeof ComparateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions': {
      id: '/excursions'
      path: '/excursions'
      fullPath: '/excursions'
      preLoaderRoute: typeof ExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergement': {
      id: '/hebergement'
      path: '/hebergement'
      fullPath: '/hebergement'
      preLoaderRoute: typeof HebergementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-voyage': {
      id: '/mon-voyage'
      path: '/mon-voyage'
      fullPath: '/mon-voyage'
      preLoaderRoute: typeof MonVoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-aeroport': {
      id: '/transport-aeroport'
      path: '/transport-aeroport'
      fullPath: '/transport-aeroport'
      preLoaderRoute: typeof TransportAeroportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/cmi-callback': {
      id: '/api/checkout/cmi-callback'
      path: '/api/checkout/cmi-callback'
      fullPath: '/api/checkout/cmi-callback'
      preLoaderRoute: typeof ApiCheckoutCmiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/stripe-webhook': {
      id: '/api/checkout/stripe-webhook'
      path: '/api/checkout/stripe-webhook'
      fullPath: '/api/checkout/stripe-webhook'
      preLoaderRoute: typeof ApiCheckoutStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitsRoute: CircuitsRoute,
  ComparateurRoute: ComparateurRoute,
  ConfirmationRoute: ConfirmationRoute,
  CultureRoute: CultureRoute,
  ExcursionsRoute: ExcursionsRoute,
  HebergementRoute: HebergementRoute,
  MonVoyageRoute: MonVoyageRoute,
  PanierRoute: PanierRoute,
  TransportAeroportRoute: TransportAeroportRoute,
  ApiCheckoutCmiCallbackRoute: ApiCheckoutCmiCallbackRoute,
  ApiCheckoutStripeWebhookRoute: ApiCheckoutStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
